// Generated by scripts/fetch-presets.ts — do not edit.
import type { PresetSnapshot } from '../presets.ts';
import p_meta_llama_llama_3_1_8b_instruct from './meta-llama-llama-3-1-8b-instruct.json' with { type: 'json' };
import p_meta_llama_llama_3_3_70b_instruct from './meta-llama-llama-3-3-70b-instruct.json' with { type: 'json' };
import p_redhatai_meta_llama_3_1_405b_instruct_fp8 from './redhatai-meta-llama-3-1-405b-instruct-fp8.json' with { type: 'json' };
import p_hugging_quants_meta_llama_3_1_405b_instruct_awq_int4 from './hugging-quants-meta-llama-3-1-405b-instruct-awq-int4.json' with { type: 'json' };
import p_qwen_qwen3_8b from './qwen-qwen3-8b.json' with { type: 'json' };
import p_qwen_qwen3_32b from './qwen-qwen3-32b.json' with { type: 'json' };
import p_qwen_qwen3_30b_a3b from './qwen-qwen3-30b-a3b.json' with { type: 'json' };
import p_qwen_qwen3_235b_a22b from './qwen-qwen3-235b-a22b.json' with { type: 'json' };
import p_qwen_qwen3_235b_a22b_instruct_2507_fp8 from './qwen-qwen3-235b-a22b-instruct-2507-fp8.json' with { type: 'json' };
import p_qwen_qwen3_next_80b_a3b_instruct from './qwen-qwen3-next-80b-a3b-instruct.json' with { type: 'json' };
import p_mistralai_mixtral_8x7b_instruct_v0_1 from './mistralai-mixtral-8x7b-instruct-v0-1.json' with { type: 'json' };
import p_deepseek_ai_deepseek_v3 from './deepseek-ai-deepseek-v3.json' with { type: 'json' };
import p_deepseek_ai_deepseek_r1_0528 from './deepseek-ai-deepseek-r1-0528.json' with { type: 'json' };
import p_deepseek_ai_deepseek_v3_2 from './deepseek-ai-deepseek-v3-2.json' with { type: 'json' };
import p_nvidia_deepseek_r1_0528_fp4 from './nvidia-deepseek-r1-0528-fp4.json' with { type: 'json' };
import p_moonshotai_kimi_k2_instruct from './moonshotai-kimi-k2-instruct.json' with { type: 'json' };
import p_openai_gpt_oss_20b from './openai-gpt-oss-20b.json' with { type: 'json' };
import p_openai_gpt_oss_120b from './openai-gpt-oss-120b.json' with { type: 'json' };
import p_meta_llama_llama_4_scout_17b_16e_instruct from './meta-llama-llama-4-scout-17b-16e-instruct.json' with { type: 'json' };
import p_meta_llama_llama_4_maverick_17b_128e_instruct from './meta-llama-llama-4-maverick-17b-128e-instruct.json' with { type: 'json' };
import p_google_gemma_3_27b_it from './google-gemma-3-27b-it.json' with { type: 'json' };

export const PRESET_SNAPSHOTS: PresetSnapshot[] = [
  p_meta_llama_llama_3_1_8b_instruct as PresetSnapshot,
  p_meta_llama_llama_3_3_70b_instruct as PresetSnapshot,
  p_redhatai_meta_llama_3_1_405b_instruct_fp8 as PresetSnapshot,
  p_hugging_quants_meta_llama_3_1_405b_instruct_awq_int4 as PresetSnapshot,
  p_qwen_qwen3_8b as PresetSnapshot,
  p_qwen_qwen3_32b as PresetSnapshot,
  p_qwen_qwen3_30b_a3b as PresetSnapshot,
  p_qwen_qwen3_235b_a22b as PresetSnapshot,
  p_qwen_qwen3_235b_a22b_instruct_2507_fp8 as PresetSnapshot,
  p_qwen_qwen3_next_80b_a3b_instruct as PresetSnapshot,
  p_mistralai_mixtral_8x7b_instruct_v0_1 as PresetSnapshot,
  p_deepseek_ai_deepseek_v3 as PresetSnapshot,
  p_deepseek_ai_deepseek_r1_0528 as PresetSnapshot,
  p_deepseek_ai_deepseek_v3_2 as PresetSnapshot,
  p_nvidia_deepseek_r1_0528_fp4 as PresetSnapshot,
  p_moonshotai_kimi_k2_instruct as PresetSnapshot,
  p_openai_gpt_oss_20b as PresetSnapshot,
  p_openai_gpt_oss_120b as PresetSnapshot,
  p_meta_llama_llama_4_scout_17b_16e_instruct as PresetSnapshot,
  p_meta_llama_llama_4_maverick_17b_128e_instruct as PresetSnapshot,
  p_google_gemma_3_27b_it as PresetSnapshot,
];
